exclude: ^docs/

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml

  - repo: local
    hooks:
      - id: dotnet-format
        name: dotnet format
        entry: dotnet
        args:
          - format
          - src/EmailPipeline.sln
        language: system
        types: [c#]
        pass_filenames: false

  - repo: local
    hooks:
      - id: dotnet-test
        name: dotnet test
        entry: dotnet
        args:
          - test
          - src/EmailPipeline.sln
          - --nologo
          - --verbosity
          - minimal
        language: system
        pass_filenames: false
