version: "3.9"
services:
  api:
    build:
      context: ./src
      dockerfile: ./EmailService.Api/Dockerfile
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8080
      ConnectionStrings__Postgres: Host=postgres;Port=5432;Database=emails;Username=postgres;Password=postgres
      Redis__Connection: redis:6379
      Rabbit__Host: rabbitmq
      Rabbit__User: guest
      Rabbit__Pass: guest
      Otel__Endpoint: http://otel-collector:4317
    ports:
      - "8080:8080"
    depends_on: [postgres, rabbitmq, redis, mailhog, otel-collector]
  worker:
    build:
      context: ./src
      dockerfile: ./EmailService.Worker/Dockerfile
    environment:
      ConnectionStrings__Postgres: Host=postgres;Port=5432;Database=emails;Username=postgres;Password=postgres
      Redis__Connection: redis:6379
      Rabbit__Host: rabbitmq
      Rabbit__User: guest
      Rabbit__Pass: guest
      Smtp__Host: mailhog
      Smtp__Port: 1025
      Smtp__From: no-reply@example.com
      RateLimit__MaxPerMinute: "60"
      Idempotency__TtlSeconds: "3600"
      Otel__Endpoint: http://otel-collector:4317
    depends_on: [postgres, rabbitmq, redis, mailhog, otel-collector]
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: emails
    ports: ["5432:5432"]
  redis:
    image: redis:7
    ports: ["6379:6379"]
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
  otel-collector:
    image: otel/opentelemetry-collector:0.103.1
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"
      - "9464:9464"
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on: [otel-collector, api, worker]
